# Generated by Django 4.0.5 on 2022-06-23 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_API_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_API_app.location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='bookings',
            field=models.JSONField(default=dict),
        ),
    ]
