# Generated by Django 4.0.5 on 2022-06-23 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_API_app', '0002_appointment_location_alter_location_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.date(2022, 6, 23)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2022, 6, 23, 16, 12, 44, 593740)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.TimeField(default=datetime.time(15, 12, 44, 593740)),
        ),
    ]
