# Generated by Django 4.0.5 on 2022-06-23 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_API_app', '0004_alter_appointment_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='bookings',
        ),
        migrations.AddField(
            model_name='location',
            name='work_schedule',
            field=models.ManyToManyField(to='main_API_app.schedule'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2022, 6, 23, 21, 5, 58, 120290)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.TimeField(default=datetime.time(20, 5, 58, 120290)),
        ),
    ]
