# Generated by Django 4.0.5 on 2022-06-24 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_API_app', '0005_remove_location_bookings_location_work_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.date(2022, 6, 24)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2022, 6, 24, 15, 50, 53, 144378)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.TimeField(default=datetime.time(14, 50, 53, 144378)),
        ),
        migrations.AlterField(
            model_name='worker',
            name='work_schedule',
            field=models.ManyToManyField(blank=True, to='main_API_app.schedule'),
        ),
        migrations.AlterUniqueTogether(
            name='worker',
            unique_together={('first_name', 'last_name', 'specialty')},
        ),
    ]
