# Generated by Django 4.0.5 on 2022-06-24 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_API_app', '0006_alter_appointment_date_alter_appointment_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='schedule_ids',
            field=models.JSONField(blank=True, default='1'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.localtime),
        ),
    ]
