# Generated by Django 4.0.5 on 2022-06-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_API_app', '0007_worker_schedule_ids_alter_appointment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='schedule_ids',
            field=models.JSONField(blank=True, default='1'),
        ),
        migrations.AlterField(
            model_name='location',
            name='work_schedule',
            field=models.ManyToManyField(blank=True, to='main_API_app.schedule'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('name', 'address')},
        ),
    ]
