# Generated by Django 4.0.5 on 2022-06-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_API_app', '0008_location_schedule_ids_alter_location_work_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='locations',
            field=models.ManyToManyField(to='main_API_app.location'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='workers',
            field=models.ManyToManyField(to='main_API_app.worker'),
        ),
    ]
