# Generated by Django 4.0.5 on 2022-06-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_API_app', '0009_schedule_locations_schedule_workers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='locations',
            field=models.ManyToManyField(blank=True, to='main_API_app.location'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='weekday',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default='Monday'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='workers',
            field=models.ManyToManyField(blank=True, to='main_API_app.worker'),
        ),
    ]
